language: php

sudo: false

before_install:
  - composer self-update

before_script: echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --dev
  - cp .env.dist .env

script: phpunit -c app

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      script: bin/phpunit --coverage-clover build/logs/clover.xml
  fast_finish: true