language: php

sudo: false

before_install:
    - composer self-update

before_script: echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install --dev
    - cp .env.dist .env

script: phpunit -c app

matrix:
    include:
        # memcached not available for php 7 on Travis
        # JSON-API example requires a minimum of 5.5.9
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.5
        - php: 5.6
    fast_finish: true