security:
  firewalls:
    default:
      request_matcher: swagger.security.request_matcher
      stateless: true
      simple_preauth:
        authenticator: jwt.authenticator
      provider: jwt

  providers:
    jwt:
      id: jwt.user_provider

