security:
  firewalls:
    default:
      request_matcher: swagger.security.request_matcher
      stateless: true
      simple_preauth:
        authenticator: jwt.authenticator
        provider: jwt
    anonymous:
      anonymous: ~

  providers:
    jwt:
      id: jwt.user_provider

  role_hierarchy:
      ROLE_USER: [IS_AUTHENTICATED_FULLY]
      ROLE_ADMIN: [ROLE_USER]