security:
  firewalls:
    default:
      request_matcher: swagger.security.request_matcher
      stateless: true
      swagger: { rbac: true }
      jwt: ~
      provider: jwt
    anonymous:
      anonymous: ~

  providers:
    jwt:
      id: jwt.user_provider

  role_hierarchy:
      ROLE_USER: [IS_AUTHENTICATED_FULLY]
      ROLE_ADMIN: [ROLE_USER]