services:
  cache.documents:
    class: Doctrine\Common\Cache\MemcachedCache
    calls:
      - [ setNamespace, ['documents'] ]
      - [ setMemcached, ['@cache.memcached'] ]

  cache.memcached:
    class: Memcached
    calls:
        - [ addServer, [ %memcached.server%, 11211 ]]

  example.entity_service.ticket:
    class: KleijnWeb\Examples\SwaggerBundle\ServiceDeskBundle\Service\Entity\TicketService
    arguments: ['@doctrine']

  controller.repository:
    class: KleijnWeb\Examples\SwaggerBundle\ServiceDeskBundle\Controller\DescriptionRepositoryController
    arguments: ['@swagger.description.repository']

  swagger.controller.ticket:
    class: KleijnWeb\Examples\SwaggerBundle\ServiceDeskBundle\Controller\V1\TicketController
    arguments: ['@example.entity_service.ticket']